name: responsively
description: Responsively flutter widgets and utils
version: 1.0.0
author: Davood Jafari
homepage: http://Davoood.ir

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter