name: responsively
description: Bring responsive widgets to flutter! this package has some widgets to make a simple responsive ui
version: 1.0.2
homepage: https://github.com/DJafari/responsively

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter